### ISSUE TITLE
Missing service config

### ISSUE THREAD

**Issue by bashilbers** [Sylius/Calendar#12] opened 2023-02-09 15:07 UTC
This line: https://github.com/Sylius/Calendar/blob/v0.4.0/src/DependencyInjection/SyliusCalendarExtension.php#L26

Is causing this: 
```
The file "services.yaml" does not exist (in: "/srv/sylius/vendor/sylius/calendar/src/DependencyInjection/../../config").                        
```

**Comment by GSadee** [comment] 2023-02-10 13:47
Hi @bashilbers, thank you for opening the issue, however, it seems that the path defined in `SyliusCalendarExtension` is correct. Looking at the error you've posted, it looks like the problem could be somewhere else, you have `srv` there instead of `src` 🤔 
I'm closing the issue as it looks like it is not connected with this repository, but feel free to reopen it or open a new one if you confirm that the problem is in our Calendar 😃

**Closed as completed by GSadee** 2023-02-10 13:47 UTC
Labels: Help Wanted
